### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by kpkrima** [douglasdcm/chatbot_for_movies#1]

**Comment by kpkrima** [comment]
ptwiki_20180420_100d.txt.bz2 what is that file?

**Comment by kpkrima** [comment]
or can you explain that part how can i created that file?

**Comment by douglasdcm** [comment]
Hi, thank you for the question. It is the embedding file that is used to train the model. Let me know if you can download it using this
link

https://drive.google.com/file/d/11TxVJZH2vzPxoblhgkUIHS4O6UK4RilH/view?usp=sharing

**Comment by kpkrima** [comment]
Hello Can you tell me which is the main file that I can use. Which is the main file?  Sent from Mail for Windows 10 From: douglasdcmSent: Sunday, August 08, 2021 22:54To: douglasdcm/chatbot_for_moviesCc: kpkrima; AuthorSubject: Re: [douglasdcm/chatbot_for_movies] hello (#1) Hi, thank you for the question. It is the embedding file that is used to tray the model. Let me know if you can download it using thislinkhttps://drive.google.com/file/d/11TxVJZH2vzPxoblhgkUIHS4O6UK4RilH/view?usp=sharing—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
