### ISSUE TITLE
which file is main file for this project? i am confused?

### ISSUE THREAD

**Issue by kpkrima** [douglasdcm/chatbot_for_movies#2]

**Comment by douglasdcm** [comment]
Hi, could you download the bz2 file? You need to download it and change the function to False
#The embedding is already downloaded
#Change to True to download
download_embedding(False)

If you are retraining the chat bot it is necessary to use the notebooks following the order of the files 001, 002... and maybe the notebooks will need to be adapted depending on your dataset. Check for more info in the Attention session of the README.
https://github.com/douglasdcm/chatbot_for_movies#attention

I hope this will help you.
Let me know if you have more questions. :)

**Comment by kpkrima** [comment]
Yes i download but i did not follow your nothbook sequel
