### ISSUE TITLE
--------------------------------------------------------------------------- StopIteration                             Traceback (most recent call last) <ipython-input-63-d5e9e2d65296> in <module> ----> 1 conversation = get_the_next_conversation(conversations)       2 conversation  <ipython-input-45-cdb994193f4c> in get_the_next_conversation(conversations)       3     keys_view = conversations.keys()       4     keys_iterator = iter(keys_view) ----> 5     conversation = next(keys_iterator)       6     return conversation  StopIteration:

### ISSUE THREAD

**Issue by kpkrima** [douglasdcm/chatbot_for_movies#3]
---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
<ipython-input-63-d5e9e2d65296> in <module>
----> 1 conversation = get_the_next_conversation(conversations)
      2 conversation

<ipython-input-45-cdb994193f4c> in get_the_next_conversation(conversations)
      3     keys_view = conversations.keys()
      4     keys_iterator = iter(keys_view)
----> 5     conversation = next(keys_iterator)
      6     return conversation

StopIteration:

**Comment by douglasdcm** [comment]
I didn't get this message. Could you explain more, please? Is it an error? In wich part of the code/notebook?

**Comment by kpkrima** [comment]
Yes this was an error
